import Head from 'next/head';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trip-Report</title>
        <meta name="description" content="Generated by Lisa :)" />
      </Head>
      <Hero />
    </div>
  );
}
